export class Reservation {
  ID: number
  teamID: number
  nr: string
  date: string
  rez_number: number
  clerk: string
  sia: string
  regnr: string
  client_name: string
  client_surname: string
  client_pk: number
  clientID: number
  client_address: string
  passport: string
  passportTill: string
  vadapl: string
  vadaplTill: string
  telnr: string
  email: string
  additionalDriver: string
  additionalDriverID: number
  additionals: string
  additionalsPrice: string
  additionalsPerday: string
  car: string
  carLVnumber: string
  caryear: number
  complect: string
  tehapltype: string
  tehapl: string
  tank: string
  fueltype: string
  km: number
  maxkm: string
  TA: string
  carFullPrice: number
  carChassisNumber: string
  from_place: string
  from_time: string
  to_place: string
  to_time: string
  abroad: string
  priceIsFull: number
  price_day: number
  rent_days: number
  price_sum: number
  rezDiscount: number
  alreadyPaid: number
  vat: number
  paid_with: string
  rek_nr: string
  security_money: number
  security_money_with: string
  securityMoneyCardNr: string
  securityMoneyCardValidTill: string
  selfrisk: number
  cancelled: number
  cancel_comment: string
  cancel_by: string
  carID: number
}
